### ISSUE TITLE
Символ с кодом 60

### ISSUE THREAD

**Issue by spogozhev** [Karkusha23/PEWM#1]
https://github.com/Karkusha23/PEWM/blob/a07eaa20aa169ced491fca95021e4f95494fd4ad/Homeworks/Char_Ackermann(27.09.21)/char.bat#L3

Посмотрите что такое символ с кодом 60 и надо или отдельно обрабатывать или подумать как иначе сделать так чтобы программа выводила символ.

**Comment by Karkusha23** [comment]
Символы до 126 включительно выводятся корректно + функция Аккермана теперь работает
